name: Quality Validation

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'courses/**'
      - 'templates/**'
      - 'scripts/**'
      - '.cursorrules'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'courses/**'
      - 'templates/**'
      - 'scripts/**'
      - '.cursorrules'

jobs:
  quality-validation:
    runs-on: ubuntu-latest
    name: Validation
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
                        - name: Setup environment
                    run: |
                      echo "Setting up validation environment..."
                      chmod +x scripts/validate.sh
          
                        - name: Run Cursor AI validation
                    run: |
                      echo "=== Running Cursor AI Quality Validation ==="
                      ./scripts/validate.sh
          
      - name: Check template compliance
        run: |
          echo "=== Checking Template Compliance ==="
          
          # Check if all required templates exist
          if [ ! -f "templates/course-template.md" ]; then
            echo "❌ Course template missing"
            exit 1
          fi
          
          if [ ! -f "templates/translation-template.md" ]; then
            echo "❌ Translation template missing"
            exit 1
          fi
          
          if [ ! -f "templates/quality-template.md" ]; then
            echo "❌ Quality template missing"
            exit 1
          fi
          
          echo "✅ All templates present"
          
      - name: Validate cross-references
        run: |
          echo "=== Validating Template Cross-References ==="
          
          # Check for cross-references in templates
          if ! grep -q "Related Templates" templates/course-template.md; then
            echo "❌ Course template missing cross-references"
            exit 1
          fi
          
          if ! grep -q "Related Templates" templates/translation-template.md; then
            echo "❌ Translation template missing cross-references"
            exit 1
          fi
          
          if ! grep -q "Related Templates" templates/quality-template.md; then
            echo "❌ Quality template missing cross-references"
            exit 1
          fi
          
          echo "✅ All templates have cross-references"
          
      - name: Check .cursorrules compliance
        run: |
          echo "=== Checking .cursorrules Compliance ==="
          
          if [ ! -f ".cursorrules" ]; then
            echo "❌ .cursorrules file missing"
            exit 1
          fi
          
          if ! grep -q "Template System Requirements" .cursorrules; then
            echo "❌ .cursorrules missing template system requirements"
            exit 1
          fi
          
          if ! grep -q "Unified Quality System" .cursorrules; then
            echo "❌ .cursorrules missing unified quality system reference"
            exit 1
          fi
          
          echo "✅ .cursorrules compliance verified"
          
      - name: Validate file structure
        run: |
          echo "=== Validating File Structure ==="
          
          # Check if courses follow correct structure
          for course_dir in courses/*/; do
            if [ -d "$course_dir" ]; then
              course_name=$(basename "$course_dir")
              echo "Checking course: $course_name"
              
              # Check for English directory
              if [ ! -d "$course_dir/en" ]; then
                echo "❌ English directory missing for $course_name"
                exit 1
              fi
              
              # Check for lesson files
              lesson_count=$(find "$course_dir/en" -name "lesson-*.md" | wc -l)
              if [ $lesson_count -eq 0 ]; then
                echo "❌ No lesson files found for $course_name"
                exit 1
              fi
              
              echo "✅ Course $course_name structure valid"
            fi
          done
          
      - name: Quality validation summary
        run: |
          echo "=== QUALITY VALIDATION SUMMARY ==="
          echo "✅ Template compliance verified"
          echo "✅ Cross-references validated"
          echo "✅ .cursorrules compliance checked"
          echo "✅ File structure validated"
          echo "✅ Cursor AI validation passed"
          echo ""
          echo "🎉 All quality checks passed!" 